name: Run Postman Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman newman-reporter-junit

      - name: Run Postman Collection
        run: |
          mkdir -p newman # 
          newman run "Your Store API testing - Technical Test.postman_collection.json" \
            --environment "fakestoreapi-test_env.postman_environment.json" \
            --reporters cli,junit \
            --reporter-junit-export newman/results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-results
          path: newman/results.xml 
